appname = facturacion_electronica_mid
httpport = ${FACTURACION_ELECTRONICA_MID_HTTPPORT}
runmode = ${FACTURACION_ELECTRONICA_MID_RUN_MODE||prod}
autorender = false
copyrequestbody = true
EnableDocs = true
parameterStore = ${PARAMETER_STORE}
ProtocolAdmin=${FACTURACION_ELECTRONICA_MID_PROTOCOL_ADMIN}
TercerosService= ${FACTURACION_ELECTRONICA_MID_TERCEROS_SERVICE}
BusserviciosBasePath = ${FACTURACION_ELECTRONICA_MID_BUSSERVICIOS_WSO2_SERVICE}
TerceroPagoPath = ${FACTURACION_ELECTRONICA_MID_WSO2_TERCERO_PAGO_PATH}
SofiaService = ${FACTURACION_ELECTRONICA_MID_SOFIA_SERVICE}